credentials:
  usernames:
    student1:
      email: "student@stemquest.com"
      name: "STEM Explorer"
      password: "$2b$12$4K6hfM0236nsd2Zaq65.OuyyFfs3FmRCnR/KcdAh0NuL.Cgii7fP."
    admin:
      email: "admin@stemquest.com"
      name: "Lead Mentor"
      password: "$2b$12$4K6hfM0236nsd2Zaq65.OuyyFfs3FmRCnR/KcdAh0NuL.Cgii7fP."

cookie:
  expiry_days: 30
  key: "stem_quest_signature_key"
  name: "stem_quest_auth_cookie"

preauthorized:
  emails:
    - "hackathon_judge@example.com"