[theme]
primaryColor = "#f5c600"
backgroundColor = "#f4f4f4"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"
font = "serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false